<?php
/*starting a session, this allows you to store data in $_SESSION['data'] in any of your components*/
session_start();
//echo ini_get("session.gc_maxlifetime"), "\n";

/** BELOW ARE THE REQUIRED DEPENDENCIES FOR OZI SCRIPT, PLUGIN AND LIBRARIES ARE TO BE UNCOMMENTED IF NOT IN USE. You Can Add New Labraries If You Know How It Works.. Learn More At https://ozi.com.ng */

/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/

//get more plugins as you wish

//Getting mail_agent
//require 'system_files/plugins/mail_agent/index.php';

//Getting Carbon
//require 'system_files/plugins/carbon/index.php';

/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/



/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/
/*==== LIBRARIES ==============*/

//calling app router Lib
require "system_files/libraries/router.php";

//calling cssd lib
require "system_files/libraries/cssd.php";

//calling jsd lib
require "system_files/libraries/jsd.php";

//calling iosMedia lib
require "system_files/libraries/ios_media.php";

/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */
/*====END OF ======== LIBRARIES */











/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/
/*==== WIDGETs ==============*/

    //calling FAB lib
    //require "assets/widgets/fab.php";
    //require "assets/widgets/navbar.php";
    require "system_files/widgets/cardItems.php";

/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */
/*====END OF ======== WIDGETS */











/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/

//006 Getting the file that is required to for building your app screen
require 'view.php';

//003 Getting required file for your uert interface (UI) design
require 'ui_config.php';

/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/