<?php
/*starting a session, this allows you to store data in $_SESSION['data'] in any of your components*/
session_start();
//echo ini_get("session.gc_maxlifetime"), "\n";

/** BELOW ARE THE REQUIRED DEPENDENCIES FOR OZI SCRIPT, PLUGIN AND LIBRARIES ARE TO BE UNCOMMENTED IF NOT IN USE. You Can Add New Labraries If You Know How It Works.. Learn More At https://ozi.com.ng */

/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/
/*========  PLUGIN'S ============*/

//get more plugins as you wish

//Getting mail_agent
//require 'assets/plugins/mail_agent/index.php';

//Getting Carbon
//require 'assets/plugins/carbon/index.php';

/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/
/*========  END OF PLUGIN'S ============*/









/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/
/*==== WIDGETS ==============*/

//getting modal 
require 'assets/widgets/modal.php';

//getting fab widget
//require 'assets/widgets/fab.php';

/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */
/*====END OF ========WIDGETS */

/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/

//006 Getting the file that is required to for building your app screen
require 'view.php';

//005 calling default app router logic
require "assets/libraries/router.php";

//003 Getting required file for your uert interface (UI) design
require 'ui_config.php';

//002 Getting the file that is required for handling the back end request
require 'create_bk_request.php';

//001 Getting the file required for calling back end request
require 'call_bk_request.php';

/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
/*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/